spring:
  application:
    name: buer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.buer.boot1.entity

# pageHelper插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

girl:
  cupSize: B
  age: 18
