spring:
  application:
    name: buer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: mysql://localhost:3306/test

server:
  port: 80

girl:
  cupSize: A
  age: 18
